# Generated by Django 2.1.7 on 2019-03-19 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('teamAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdminTeams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('teamMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='teamMember',
            field=models.ManyToManyField(related_name='MemberTeams', through='Teams.TeamUserMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
