# Generated by Django 2.1.7 on 2019-03-19 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('teamMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('admin', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='TeamsList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Teams.TeamsList'),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamMember',
            field=models.ManyToManyField(through='Teams.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='teamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Teams'),
        ),
    ]
