# Generated by Django 2.2.dev20181210142849 on 2019-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=30)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Planning'), (2, 'Progressing'), (3, 'Done')])),
                ('favorite', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasks', models.ManyToManyField(to='Teams.Team')),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
