# Generated by Django 2.1.7 on 2019-03-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20190314_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='team',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
    ]
