# Generated by Django 2.1.7 on 2019-03-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20190325_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Teams.Tasks'),
        ),
    ]
