# Generated by Django 2.1.7 on 2019-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_auto_20190325_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
