# Generated by Django 2.1.7 on 2019-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0005_auto_20190331_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusermembership',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
